# Generated by Django 3.2 on 2021-04-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0002_userdb_openid2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='openId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='openId2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
