# Generated by Django 3.2 on 2021-04-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0003_auto_20210430_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='openId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='openId2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
