# Generated by Django 3.2 on 2021-04-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garbage', '0004_auto_20210430_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdb',
            name='face',
        ),
    ]
